# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeddApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeddApp
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  target 'WeddAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeddAppUITests' do
    # Pods for testing
  end

end
